CREATE DATABASE COMPANY_DB;
USE COMPANY_DB;
CREATE TABLE EMPLPOYEES(
		employee_id int primary key not null,
        first_name VARCHAR(50),
        last_name VARCHAR(50),
        date_of_birth DATE,
        hire_date DATE,
        salary Double,
        department VARCHAR(50)
        );
INSERT INTO EMPLPOYEES(employee_id,first_name,last_name,date_of_birth,hire_date,salary,department)
VALUE
(1, 'John', 'Doe', '1985-05-15', '2010-01-10', 55000.00, 'HR'),
(2, 'Jane', 'Smith', '1990-08-25', '2015-03-20', 65000.50, 'IT'),
(3, 'Emily', 'Johnson', '1987-11-30', '2012-06-25', 72000.75, 'Finance'),
(4, 'Michael', 'Williams', '1992-01-10', '2018-11-01', 48000.00, 'HR'),
(5, 'Sophia', 'Brown', '1995-04-14', '2020-02-15', 55000.25, 'IT');
SELECT *FROM EMPLPOYEES;
SELECT COUNT(employee_id) FROM EMPLPOYEES;
SELECT *FROM EMPLPOYEES WHERE SALARY > 60000 ORDER BY SALARY DESC;
SELECT AVG(SALARY) FROM EMPLPOYEES where department = 'HR'; 
SELECT *FROM EMPLPOYEES WHERE DATE_OF_BIRTH < '1987-11-30';
UPDATE EMPLPOYEES SET SALARY = 52000 WHERE employee_id=4;
DELETE FROM EMPLPOYEES WHERE employee_id = 3;
SELECT SUM(SALARY) FROM EMPLPOYEES
WHERE DEPARTMENT = 'IT';
SELECT MAX(SALARY) FROM EMPLPOYEES; /*65000*/
INSERT INTO EMPLPOYEES(employee_id,first_name,last_name,date_of_birth,hire_date,salary,department)
VALUE
(3, 'Emily', 'Johnson', '1987-11-30', '2012-06-25', 72000.75, 'Finance');
SELECT MAX(SALARY) FROM EMPLPOYEES;  /*72000*/


-- MAX SALARY FROM EACH DEPARTMENTS
SELECT DEPARTMENT, MAX(SALARY) FROM EMPLPOYEES GROUP BY DEPARTMENT;

-- DELETE FROM EMPLPOYEES WHERE employee_id = ;

-- SHOWS HOW MANY EMPLOYEES ARE THERE IN EACH DEPARTMENT
SELECT DEPARTMENT, COUNT(employee_id) FROM EMPLPOYEES GROUP BY (DEPARTMENT) 
HAVING DEPARTMENT='IT'; -- IT DEPARTMENT E KOTOJON ACHE
-- AFTER ADDING THE UPPER LINE IT SHOWS HOW MANY EMPLOYEES ARE THERE IN 'IT' DEPARTMENT


SELECT DEPARTMENT, COUNT(*) FROM EMPLPOYEES GROUP BY DEPARTMENT ORDER BY MAX(FIRST_NAME) DESC;

